name: Challenge1
on: 
  workflow_dispatch:

jobs:
  job1:
    name: Environment Info
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          date
          pwd
          ls -la

  job2:
    name: Python Setup and Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check Python Version
        run: python --version

      - name: Set up pandas
        run: pip install pandas

      - name: Create artifact
        run: |
          echo "# This is my python artifact" > artifact.py
          python artifact.py

