name: tutorial1
on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check Python version
        run: python --version

      - name: step1
        run: echo "Hello from job1"

  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: step2
        run: echo "hellow from job 2"

  job3:
    name: job3
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: echo "hello from job 3"

  job4:
    name: job4
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: step4
        run: echo "This is job4, after job1 and job2"
"

